### PR TITLE
Fix IBM Plex Mono font is missing in Safari

### LINKED ISSUE #1044: IBM Plex Mono font is missing
**Describe the bug**
Code renders in the browser default monospace font when IBM Plex Mono is selected.

**To Reproduce**
Paste code.
⚙️ ➔ Editor ➔ Font ➔ IBM Plex Mono

**Expected behavior**
The code font should change to IBM Plex Mono.

**Screenshots**
Screenshot 2020-06-27 at 23 24 02

**Info**

- OS [e.g. macOS, Linux, Windows, iOS]: macOS 10.15.4
- Browser [e.g. Chrome, Safari, Firefox]: Safari, Safari Technical Preview

### PR DESCRIPTION
**Pull request by seagalputra**
According to #1044 issue, IBM Plex Mono won't loaded properly in Safari web browser. I remove some attributes when load font with `@font-face` and now it's loaded properly.

Before
image

After
Screen Shot 2020-08-13 at 10 58 21

Fixes #1044

### CODE REVIEW

File: components/style/Font.js [hunk 1]
```diff
@@ -75,15 +75,9 @@ export default () => (
       /* latin */
       @font-face {
         font-family: 'IBM Plex Mono';
-        font-display: swap;
-        font-style: italic;
```
Comment (mfix22) [inline components/style/Font.js:79]: Looks like all you actually need to remove is `font-style`.

Comment (seagalputra) [reply components/style/Font.js:79]: Ok, I already fixed this
